project:
  type: website
  output-dir: docs
  resources: 
    - files/resume.pdf

website:
  title: "Dylan Dodds"
  site-url: https://ida314.github.io
  description: "Dylan's personal technical blog"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: cv.md
        text: Resume
      - posts.md
    right:
      - icon: rss
        href: posts.xml


format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
